export interface BlogArticle {
  id: string;
  title: string;
  excerpt: string;
  category: 'Himalayan Treks' | 'Camping' | 'Backpacking' | 'Solo Travel' | 'Gear Reviews' | 'Travel Tips' | 'Adventure Stories';
  readTime: string;
  date: string;
  image: string;
  content: string[]; // array of paragraphs
  author: string;
  tags: string[];
  relatedPostIds: string[];
}

export const blogsData: BlogArticle[] = [
  {
    id: 'layering-guide',
    title: 'The Himalayan Layering Guide: How to Dress for Sub-Zero',
    excerpt: 'Dressing for high altitudes is a science. Learn the 3-layer system—base, insulation, and outer shell—to stay warm and dry in sub-zero winds.',
    category: 'Gear Reviews',
    readTime: '6 min read',
    date: 'July 10, 2026',
    image: 'https://images.unsplash.com/photo-1526772662000-3f88f10405ff?auto=format&fit=crop&w=800&q=80',
    author: 'Suraj Singh',
    tags: ['Trek Gear', 'Himalayas', 'Winter Clothing', 'Layering System'],
    relatedPostIds: ['footwear-guide', 'acclimatization-science'],
    content: [
      'When trekking in the Himalayas, temperature fluctuations can be extreme. You might start a sunny morning in a t-shirt at 8,000 feet, and end the night shivering in a tent at 14,000 feet with temperatures dropping below freezing. To stay comfortable and safe, relying on one heavy jacket is a mistake. Instead, experienced mountaineers use the three-layer system.',
      'The Base Layer is the layer in direct contact with your skin. Its primary job is moisture management—pulling sweat away from your skin so you do not get chilled when you stop moving. Look for synthetic fabrics (like polyester) or merino wool. Never wear cotton as a base layer; it absorbs sweat, stays wet, and drains your body heat.',
      'The Insulation Layer goes over the base layer. Its job is to trap the heat generated by your body. Popular options include fleece jackets, down jackets, or synthetic insulated jackets. Down offers the best warmth-to-weight ratio and compresses tightly into your pack, but loses insulation properties if it gets wet. Fleece is highly breathable and dries quickly.',
      'The Outer Shell (Weather Barrier) is your shield against rain, snow, and wind. High-altitude winds can quickly cause hypothermia if they penetrate your clothing. A good outer shell must be windproof, waterproof, and breathable. GORE-TEX or equivalent technical membranes are ideal as they block external moisture while letting sweat vapor escape.',
      'By combining these three layers, you can easily adapt to changing trail conditions. If you get hot while climbing a steep ridge, pack away your insulation layer. If a cold wind picks up, throw on your outer shell. This modular approach is key to enjoying your Himalayan journey.'
    ]
  },
  {
    id: 'acclimatization-science',
    title: 'High-Altitude Acclimatization: Science and Safety',
    excerpt: 'Understand how your body adapts to thin air, what causes Acute Mountain Sickness (AMS), and the rules to prevent it on high passes.',
    category: 'Travel Tips',
    readTime: '8 min read',
    date: 'June 28, 2026',
    image: 'https://images.unsplash.com/photo-1454496522488-7a8e488e8606?auto=format&fit=crop&w=800&q=80',
    author: 'Dr. Rahul Sharma',
    tags: ['Safety First', 'AMS Risks', 'Acclimatization', 'Altitude Guide'],
    relatedPostIds: ['layering-guide', 'leave-no-trace'],
    content: [
      'As you climb higher, the atmospheric pressure decreases, meaning there are fewer oxygen molecules in each breath you take. Above 10,000 feet, thin air becomes a critical factor. Acclimatization is the process by which your body adapts to this lower oxygen concentration. Understanding this science is essential for any high-altitude trekker.',
      'When you first arrive at high altitude, your body senses the oxygen drop and triggers immediate compensations. Your heart rate and breathing rate increase to deliver more oxygen to your tissues. Over the next few days, your kidneys produce more EPO, stimulating your bone marrow to create more red blood cells, enhancing your oxygen-carrying capacity.',
      'If you ascend too quickly, these adaptations cannot keep pace, leading to Acute Mountain Sickness (AMS). Common symptoms of mild AMS include a throbbing headache, fatigue, dizziness, loss of appetite, and nausea. AMS is your body’s warning system. Ignoring it can lead to life-threatening conditions like High Altitude Pulmonary Edema (HAPE) or Cerebral Edema (HACE).',
      'To prevent AMS, follow the golden rules of high-altitude travel. First, climb gradually. Do not increase your sleeping altitude by more than 1,000 to 1,500 feet per day once above 10,000 feet. Second, follow the mountaineering rule: "Climb high, sleep low"—climb to a higher altitude during the day for exercise and descend to a lower altitude to sleep.',
      'Lastly, stay hydrated. High-altitude air is extremely dry, and your body loses water rapidly through heavy breathing. Drink 4 to 5 liters of water daily. Avoid alcohol, sleeping pills, and heavy exertion during your first 24 hours at base camp. If symptoms of AMS persist or worsen, the only cure is immediate descent.'
    ]
  },
  {
    id: 'leave-no-trace',
    title: 'Leave No Trace: The Code of Sustainable Trekking',
    excerpt: 'The Himalayas face a massive garbage crisis. Practice the 7 Leave No Trace principles to protect fragile alpine ecosystems.',
    category: 'Camping',
    readTime: '5 min read',
    date: 'May 15, 2026',
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=800&q=80',
    author: 'Suraj Singh',
    tags: ['Eco Friendly', 'Himalayas CleanUp', 'Outdoor Ethics', 'Leave No Trace'],
    relatedPostIds: ['himalayan-culture', 'acclimatization-science'],
    content: [
      'The surge of trekking in India has brought tourism money to remote villages, but it has also brought a wave of plastic waste. Fragile alpine ecosystems take decades to recover from pollution, and cold temperatures slow down decomposition. To protect these wild areas, every explorer must pledge to the seven principles of Leave No Trace (LNT).',
      '1. Plan Ahead and Prepare: Know the regulations of the park, prepare for extreme weather, and repackage food into reusable containers to minimize packaging waste before hitting the trail.',
      '2. Travel and Camp on Durable Surfaces: Stick strictly to marked trails to prevent soil erosion. Avoid walking on delicate wildflowers, and pitch tents on established campsites or durable rock, gravel, or dry grass patches.',
      '3. Dispose of Waste Properly: Pack it in, pack it out. Carry all dry waste (wrappers, cans, plastic) down to the base town. For organic waste, dig a cat-hole 6 to 8 inches deep, at least 200 feet away from lakes and streams, and bury it completely.',
      '4. Leave What You Find: Leave rocks, plants, and archaeological artifacts as you find them. Never pick wildflowers, carve names on tree bark, or take stones home as souvenirs.',
      '5. Minimize Campfire Impacts: Use a camp stove for cooking rather than building wood fires. Gathering firewood depletes the forest floor of natural nutrients and destroys animal habitats.',
      '6. Respect Wildlife: Observe mountain animals from a distance. Never feed birds or mammals, as this disrupts their natural foraging behaviors and makes them dependent on humans.',
      '7. Be Considerate of Other Visitors: Yield to uphill hikers, keep noise levels low (no portable speakers on the trail), and let the sounds of nature prevail.'
    ]
  },
  {
    id: 'himalayan-culture',
    title: 'Pastoral Communities: Life in High Altitude Villages',
    excerpt: 'Meet the Gaddi, Gujjar, and Bhotia shepherds. Discover how homestay tourism supports local families and protects heritage.',
    category: 'Adventure Stories',
    readTime: '7 min read',
    date: 'April 20, 2026',
    image: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=800&q=80',
    author: 'Priya Mukherjee',
    tags: ['Ethical Tourism', 'Mountain Villages', 'Culture Diary', 'Himachal Life'],
    relatedPostIds: ['leave-no-trace', 'layering-guide'],
    content: [
      'The Indian Himalayas are home to rich pastoral communities that have lived in harmony with the mountains for centuries. From the nomadic Gaddi and Gujjar shepherds of Himachal and Uttarakhand to the Bhotia traders of Sikkim, their cultures are deeply connected to the seasonal cycles of the mountains.',
      'Shepherds practice transhumance—moving their herds of sheep and goats to high alpine pastures (bugyals) during the summers, and descending to warmer river valleys in the winters. Their lives require incredible resilience, navigating steep passes and living in stone shelter huts (kothis) under open skies.',
      'When you choose to trek ethically, you interact directly with these communities. Staying at local family homestays rather than foreign-owned concrete hotels ensures your tourism money directly supports the local economy. It also offers an authentic window into mountain life—sharing hot meals cooked on traditional mud stoves (chulhas).',
      'To respect local cultures, always ask for permission before taking photos of individuals, dress modestly in village settings, and respect local religious sites (for example, always walk clockwise around Buddhist stupas and prayer wheels). By traveling mindfully, we preserve these ancient cultures for generations to come.'
    ]
  },
  {
    id: 'footwear-guide',
    title: 'How to Choose the Right Trekking Shoes',
    excerpt: 'Your shoes can make or break your trek. Learn how to select the right fit, sole grip, ankle support, and avoid blisters.',
    category: 'Gear Reviews',
    readTime: '5 min read',
    date: 'March 12, 2026',
    image: 'https://images.unsplash.com/photo-1611637576109-b6f76185ec9b?auto=format&fit=crop&w=800&q=80',
    author: 'Suraj Singh',
    tags: ['Trek Boots', 'Vibram Grip', 'Waterproofing', 'Footwear Guide'],
    relatedPostIds: ['layering-guide', 'himalayan-culture'],
    content: [
      'Your feet are your engine on a trek. A bad pair of shoes can result in painful blisters, lost toenails, or even sprained ankles, cutting your adventure short. Choosing the right trekking shoe is the most important gear decision you will make.',
      'The first feature to check is Ankle Support. While trail running shoes or low-cut shoes are fine for flat walks, high-altitude treks require carrying a 10kg backpack over rocky, uneven trails. A mid-to-high cut shoe wraps around your ankle joint, protecting it from twisting on loose boulders or slippery scree slope descents.',
      'Next is the Sole Grip. Look for deep, multidirectional lugs (grooves) made of high-quality rubber (like Vibram). These lugs dig into mud, snow, and gravel, preventing slips. The flexibility of the sole is also key: a stiff sole protects your foot arches from fatigue on rocky trails, while a flexible sole is better for easy, flat walks.',
      'Waterproofing is vital for Himalayan crossovers where you might cross shallow streams or walk through wet snow. Look for shoes with a waterproof membrane (like GORE-TEX) and a gusseted tongue (where the tongue is stitched to the sides of the shoe) to prevent water from seeping in through the lace eyelets.',
      'Lastly, pay attention to the fit. Always buy trekking shoes one size larger than your regular daily shoes. Your feet naturally swell during long walks, and walking downhill pushes your toes forward. Having extra toe room prevents painful bruised toenails. Always wear your new shoes on short walks to "break them in" before starting a multi-day trek!'
    ]
  }
];
